### ISSUE TITLE
Typo in MNEMONIC

### ISSUE THREAD

**Issue by djsatok** [aurora-is-near/aurora-examples#19]
https://github.com/aurora-is-near/aurora-examples/blob/main/truffle/erc721-example/truffle-config.js#L4

**Comment by 0x3bfc** [comment]
Thanks @djsatok. It is fixed [here](https://github.com/aurora-is-near/aurora-examples/commit/9f8fbbdcbc19f8f86acd6f758fcc1968f6a42d34)
